######################## default configuration ####################
baseURL = "https://gregorytagny.github.io"
title = "Gregory's Portfolio"
theme = "somrat"

### Trying to change the thumbnail
image = "images/slider/slider-4.jpg"
thumbnail = "images/slider/slider-4.jpg"
featuredImage = "images/slider/slider-4.jpg"
featuredImagePreview = "images/slider/slider-4.jpg"

# disable language
disableLanguages = [] # desable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Expertise"
URL = "#service"
weight = 3

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 4

[[menu.main]]
name = "Testimonial"
URL = "#testimonial"
weight = 5

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 6


#################### default parameters ################################
[params]
logo_light = "images/logo3.png"
logo_dark = "images/logo3.png"
# Meta data
description = "Gregory's Portfolio"
author = "somrat"
# contact form action
contact_form_action = "https://formspree.io/xeqrepjg" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-167191785-1" # your id
# Google Manager
gtm_id = "GTM-5JH5W23"
gtm_datalayer = "basic"
gtm_ga = true
# Google site verification
google_site_verification = "lSEHW2YGveGAP5upiOlrPGrNr_d-kuq4tWd-SCDESHU"
# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################
[[params.social]]
icon = "fa-facebook-f" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.facebook.com/xxx"

[[params.social]]
icon = "fa-twitter" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://twitter.com/el_gregory_o"

[[params.social]]
icon = "fa-instagram" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.instagram.com/el_gregory_o/"

[[params.social]]
icon = "fa-github" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://github.com/GregoryTagny"

[[params.social]]
icon = "fa-linkedin" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
link = "https://www.linkedin.com/in/gregorytagny/"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020"
